# -*- coding: utf-8 -*-
"""Lista05Exercício04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j-wP8MvQcJI44rSunJ_OPokv2VSlIbX5
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 05

#EX04
'''#Fazendo a importação do Statistics para untilização das funções
import statistics
#Preenchendo a lista com os dados de toneladas fornecidos
tonelada = [12, 12, 14, 15, 17, 18, 18, 22, 23, 29]
#Utilizando a função MEAN para para exibir a Média aritmética simples
print('Méria aritmética simples: ', statistics.mean(tonelada))
#Utilizando a função MEDIAN para para exibir o Mediana
print('Mediana: ', statistics.median(tonelada))
#Utilizando a função STDEV para para exibir o Desvio Padrão
print('Desvio Padrão: ',statistics.stdev(tonelada))'''