# -*- coding: utf-8 -*-
"""Lista04Exercício09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uiz-zLaUVqzkCPZSyHBL329rQGHdJTU
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 4

#EX09
'''#Recebendo o número de 4 digitos
numero = int (input('Entre com um número de 4 digitos: '))

#Extraindo a unidade
unidade = numero % 10

#Retirando a unidade
numero = (numero - unidade)/10

#Extraindo a dezena
dezena = numero % 10

#Retirando a dezena
numero = (numero - dezena)/10

#Extraindo a centena
centena = numero % 10

#Retirando a centena
numero = (numero - centena)/10

#Resta o milhar
milhar = numero

#Tornando-os inteiro
dezena = int(dezena)
centena = int(centena)
milhar = int(milhar)

#Exibindo os dados
print('Unidade=', unidade, 'Dezena=', dezena, 'Centena=', centena, 'Milhar=', milhar)'''