# -*- coding: utf-8 -*-
"""Lista04Exercício07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lyU71gkUwMMffNJzCmyMatqbYz8KNLft
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 4

#EX07
'''#Recebendo o número 
num = int (input('Entre com um número de 1 a 4: '))
#Fazendo a condição para que aceite somente número de 1 a 4 e caso contrário repita o processo para receber o número
while (num < 1 or num > 4):
  print('Entrada Inválida')
  num = int (input('Entre com um número de 1 a 4: '))
#Imprimir o resultado para números digitados de 1 a 4
else:
  print('Número digitado: ', num)'''