# -*- coding: utf-8 -*-
"""Lista05Exercício06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YiGE_Tzq7bes9UbYBvYbYsKoIcdArHBJ
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 05

#EX06
'''#Recebendo as 3 notas
nota1 = int(input('Entre com a primeira nota: '))
nota2 = int(input('Entre com a segunda nota: '))
nota3 = int(input('Entre com a terceira nota: '))

#Fazendo a Média Ponderada
media_ponderada = (nota1 * 3 + nota2 * 4 + nota3 * 3) / (3 + 4 + 3)

#Validando se as notas digitadas estão dentro do intervalo de 0 a 10
if (nota1 < 0 or nota1 > 10):
  print('Nota 1 inválida')
elif (nota2 < 0 or nota2 > 10):
  print('Nota 2 inválida')
elif (nota3 < 0 or nota3 > 10):
  print('Nota 3 inválida')
else:
  #Exibindo a média ponderada
  print('Média ponderada do aluno: ', media_ponderada)'''