# -*- coding: utf-8 -*-
"""Lista06Exercício02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GY9cBFrX1skap9Hh_s4Ddk0YJG1_grHI
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 06

#EX02
#O coeficiente de relação encontrado r = 0,207, sendo ele positivo indica uma correlação desprezível