# -*- coding: utf-8 -*-
"""Lista06Exercício06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vzsDJVu-8YuJdbBfL8Z3HCVW--_wTbhl
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 06

#EX06
'''import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
dados = {
    'Produtividade':[100, 102, 105, 108, 112, 120],
    'Alimentação':[4, 5, 1, 3, 6, 2],
    'Exercícios':[1, 3, 2, 4, 5, 6],
    'Rodízio':[3, 1, 2, 6, 4, 5]
}

x = pd.DataFrame(dados, columns = ['Produtividade', 'Alimentação', 'Exercícios', 'Rodízio'])
correlacao = x.corr()
print(correlacao, '\n')


sn.heatmap(correlacao, annot=True)
plt.show()'''