# -*- coding: utf-8 -*-
"""Lista04Exercício08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h_QsBSuB7Cj1m7LWNreIFL_rezMQIIxv
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 4

'''#EX08
#Iniciando a lista e recebendo o número
lista = []
num = int (input('Entre com um número inteiro: '))

#Criando a condição WHILE para que o programa rode até o 0(Zero) seja digitado
while (num != 0):
  lista.append(num)
  print('Maior número da lista: ', max(lista))
  num = int (input('Entre com um número inteiro: '))
else:
  print('Programa encerrado')'''