# -*- coding: utf-8 -*-
"""Lista04Exercício04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MwUepV7ElXrxFaQQMevtIioHBy4wBvBM
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 4

#EX04
'''#Recebendo a medida dos 3 lados
lado1 = input('Insira a primeira medida: ')
lado2 = input('Insira a segunda medida: ')
lado3 = input('Insira a teceira medida: ')

#Condição para identificar o tipo do Triângulo
if (lado1 == lado2 and lado1 == lado3 and lado2 == lado3):
  print('Triângulo Equilátero')
if (lado1 == lado2 or lado1 == lado3 or lado2 == lado3):
  print('Triângulo Isóscele')
if (lado1 != lado2 and lado1 != lado3 and lado2 != lado3):
  print('Triângulo Escaleno')'''