# -*- coding: utf-8 -*-
"""Lista06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I0_n-S-2kPDD9-RQ73OMMKxIb59qrvRK
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 06

#EX01
'''import pandas as pd 
dados = {
    'Matemática':[60, 58, 73, 51, 21, 75, 48, 72, 75, 83, 62, 52],
    'Música':[80, 62, 70, 83, 62, 92, 79, 88, 54, 82, 64, 69]
}

x = pd.DataFrame(dados, columns = ['Matemática', 'Música'])
correlacao = x.corr()
print(correlacao)'''

#EX02
#O coeficiente de relação encontrado r = 0,207, sendo ele positivo indica uma correlação desprezível

#EX03
'''import pandas as pd 
dados = {
    'AnoServico':[2, 3, 4, 5, 4, 6, 7, 8, 8, 10],
    'Clientes':[48, 50, 56, 52, 43, 60, 62, 58, 64, 72]
}

x = pd.DataFrame(dados, columns = ['AnoServico', 'Clientes'])
correlacao = x.corr()
print(correlacao)
print('Correlação positiva e forte!')'''

#EX04
'''import pandas as pd 
dados = {
    'X':[12, 16, 18, 20, 28, 30, 40, 48, 50, 54],
    'Y':[7.2, 7.4, 7.0, 6.5, 6.6, 6.7, 6.0, 5.6, 6.0, 5.5]
}

z = pd.DataFrame(dados, columns = ['X', 'Y'])
correlacao = z.corr()
print(correlacao)
print('Correlação negativa e muito forte!')'''

#EX05
'''import pandas as pd 
import statistics

conjunto1 = {
    'X':[10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5],
    'Y':[8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68]
}

print('Conjunto 01\n')

#Utilizando a função MEAN para para exibir a Média aritmética simples
print('Média de X: ', statistics.mean(conjunto1['X']))
print('Média de Y: ', statistics.mean(conjunto1['Y']))

#Utilizando a função STDEV para para exibir o Desvio Padrão
print('Desvio Padrão de X: ',statistics.stdev(conjunto1['X']))
print('Desvio Padrão de Y: ',statistics.stdev(conjunto1['Y']))

x1 = pd.DataFrame(conjunto1, columns = ['X', 'Y'])
correlacao1 = z.corr()
print('\nCoeficiente de correlação')
print(correlacao1)
print('Correlação: positiva e forte!')

conjunto2 = {
    'X':[10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5],
    'Y':[9.14, 8.14, 8.74, 8.77, 9.26, 8.10, 6.13, 3.10, 9.13, 7.26, 4.74]
}

print('\n-----------------------------------------------------------\n')
print('Conjunto 02\n')

#Utilizando a função MEAN para para exibir a Média aritmética simples
print('Média de X: ', statistics.mean(conjunto2['X']))
print('Média de Y: ', statistics.mean(conjunto2['Y']))

#Utilizando a função STDEV para para exibir o Desvio Padrão
print('Desvio Padrão de X: ',statistics.stdev(conjunto2['X']))
print('Desvio Padrão de Y: ',statistics.stdev(conjunto2['Y']))

x2 = pd.DataFrame(conjunto2, columns = ['X', 'Y'])
correlacao2 = z.corr()
print('\nCoeficiente de correlação')
print(correlacao2)
print('Correlação: positiva e forte!')

conjunto3 = {
    'X':[10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5],
    'Y':[7.46, 6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39, 8.15, 6.42, 5.73]
}

print('\n-----------------------------------------------------------\n')
print('Conjunto 03\n')

#Utilizando a função MEAN para para exibir a Média aritmética simples
print('Média de X: ', statistics.mean(conjunto3['X']))
print('Média de Y: ', statistics.mean(conjunto3['Y']))

#Utilizando a função STDEV para para exibir o Desvio Padrão
print('Desvio Padrão de X: ',statistics.stdev(conjunto3['X']))
print('Desvio Padrão de Y: ',statistics.stdev(conjunto3['Y']))

x3 = pd.DataFrame(conjunto3, columns = ['X', 'Y'])
correlacao3 = z.corr()
print('\nCoeficiente de correlação')
print(correlacao3)
print('Correlação: positiva e forte!')

conjunto4 = {
    'X':[8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8],
    'Y':[6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25, 12.50, 5.56, 7.91, 6.89]
}

print('\n-----------------------------------------------------------\n')
print('Conjunto 04\n')

#Utilizando a função MEAN para para exibir a Média aritmética simples
print('Média de X: ', statistics.mean(conjunto4['X']))
print('Média de Y: ', statistics.mean(conjunto4['Y']))

#Utilizando a função STDEV para para exibir o Desvio Padrão
print('Desvio Padrão de X: ',statistics.stdev(conjunto4['X']))
print('Desvio Padrão de Y: ',statistics.stdev(conjunto4['Y']))

x4 = pd.DataFrame(conjunto4, columns = ['X', 'Y'])
correlacao4 = z.corr()
print('\nCoeficiente de correlação')
print(correlacao4)
print('Correlação: positiva e forte!')'''

#EX06
'''import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
dados = {
    'Produtividade':[100, 102, 105, 108, 112, 120],
    'Alimentação':[4, 5, 1, 3, 6, 2],
    'Exercícios':[1, 3, 2, 4, 5, 6],
    'Rodízio':[3, 1, 2, 6, 4, 5]
}

x = pd.DataFrame(dados, columns = ['Produtividade', 'Alimentação', 'Exercícios', 'Rodízio'])
correlacao = x.corr()
print(correlacao, '\n')


sn.heatmap(correlacao, annot=True)
plt.show()'''