# -*- coding: utf-8 -*-
"""Lista04Exercício06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nc4VQifgIqJF73axEFxwf55zNpXevjtz
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 4

#EX06
'''#Recebendo o número
numero = int (input('Insira um número: '))
#Exibindo números de 0 até o número digitado com a função RANGE
for sequencia in range(numero):
  print(sequencia)'''