# -*- coding: utf-8 -*-
"""Lista04Exercício05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LxS7t49IS3aLZDr4R3PiHMzLwA2rwHdd
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 4

#EX05
'''#Recebendo a medida dos 3 ângulos
angulo1 = int (input('Insira o primeiro ângulo: '))
angulo2 = int (input('Insira o segundo ângulo: '))
angulo3 = int (input('Insira o teceiro ângulo: '))

#Condição para identificar o tipo do Triângulo
if (angulo1 == 90 or angulo2 == 90 or angulo3 == 90):
  print('Triângulo Retângulo')
if (angulo1 > 90 or angulo2 > 90 or angulo3 > 90):
  print('Triângulo Obtusângulo')
if (angulo1 < 90 and angulo2 < 90 and angulo3 < 90):
  print('Triângulo Acutângulo')'''