# -*- coding: utf-8 -*-
"""Lista05Exercício03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y8Sek9GMmkyL2ISviyr1xuwLc7yBo2B8
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 05

#EX03
'''#Fazendo a importação do Statistics para untilização das funções
import statistics
#Preenchendo a lista com os dados de kg fornecidos
kg = [4.0, 4.5, 5.0, 5.0, 5.5, 6.0, 6.0, 6.5, 6.5, 6.5, 6.5, 7.0, 7.0, 7.0, 7.0, 7.0, 7.5, 8.5, 9.0, 9.0, 9.0, 9.5, 10.0, 10.0, 10.5, 11.0, 12.0, 12.5, 13.0, 13.0]
#Utilizando a função STDEV e MEAN para para exibir o Coeficiente de Variância
print('Coeficente de variância: ', (statistics.stdev(kg) / statistics.mean(kg)) * 100)'''