# -*- coding: utf-8 -*-
"""Lista04Exercício01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R7RjUFM23mpnHeEoRiRaYojnkGE8oHVw
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 4

#EX01
'''#Recebendo a quantidade de lado e a medida em cm
num = int (input('Entre com a quantidade de lados: '))
cm = int (input('Entre com a medida em cm: '))

#Fazendo cálculo da área
area = num * cm

#Condição para apresentar a resposta
if (num == 3):
  print('TRIÂNGULO', area,'cm')
if (num == 4):
  print('QUADRADO', area,'cm')
if (num == 5):
  print('PENTÁGONO')'''