# -*- coding: utf-8 -*-
"""Lista05Exercício05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W4HoWhXvf-4aKBvYgWcrRVUZmMsDQZfM
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 05

#EX05
'''#Fazendo a importação para utilização da função GMEAN
from scipy.stats.mstats import gmean
#Fazendo a importação do Statistics para untilização das funções
import statistics
#Iniciando a lista vazia
lista = []
#Iniciando a variavel nota com tipo inteiro
nota = int
#Condição WHILE para rodar o programa até que o código de saída seja digitado
while (nota != (-999)):
  #Recebe a nota do aluno 
  nota = int (input('Entre com a nota do aluno: '))
  #Condição para verificar se a nota digitada está entre 0 e 10
  if (nota < 0 or nota > 10):
    #Condição para finalizar o programa
    if (nota == (-999)):
      print('Programa encerrado')
    #Se a nota inserida for menor que 0 e maior que 10 exibe a mensagem de erro  
    else:
      print('Nota inválida')
  #Se a nota estiver correta e não for o código de saída a nota é inserida na lista
  else:
    lista.append(nota)
else:
  #Lista é organizada na ordem crescente
  lista.sort()
  #Utilizando a função MEAN para para exibir a Média aritmética simples
  print('Méria aritmética simples: ', statistics.mean(lista))
  #Utilizando a função HARMONIC_MEAN para para exibir a Média Harmônica
  print('Média Harmônica: ', statistics.harmonic_mean(lista))
  #Utilizando a função GMEAN para para exibir a Média Geometrica
  print('Média Geométrica: ', gmean(lista))
  #Utilizando a função MODE para para exibir a MODA
  print('Moda: ', statistics.mode(lista))
  #Utilizando a função VARIANCE para para exibir a Variância
  print('Variância: ',statistics.variance(lista))
  #Utilizando a função STDEV para para exibir o Desvio Padrão
  print('Desvio Padrão: ',statistics.stdev(lista))
  #Utilizando a função STDEV e MEAN para para exibir o Coeficiente de Variância
  print('Coeficente de variância: ', (statistics.stdev(lista) / statistics.mean(lista)) * 100)'''