# -*- coding: utf-8 -*-
"""Lista04Exercício03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/135mJssc4BmWjCfuvFAFCkGgT60E1Go-p
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 4

#EX03
'''#Recebendo os 3 números
num1 = int (input('Insira o primeiro número: '))
num2 = int (input('Insira o segundo número: '))
num3 = int (input('Insira o terceiro número: '))
#Alimentando a lista
lista = [num1, num2, num3]
#Condição para identificar números iguais
if (num1 == num2 or num1 == num3 or num2 == num3):
  print('Números repetidos')
#Se não tiver números iguais, vai exibir o maior número digitado através da função MAX
else:
  print('Maior número da lista: ', max(lista))'''