# -*- coding: utf-8 -*-
"""Lista06Exercício04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y891r8xhoykpDkutqBi_qjqjSEPiZuWs
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 06

#EX04
'''import pandas as pd 
dados = {
    'X':[12, 16, 18, 20, 28, 30, 40, 48, 50, 54],
    'Y':[7.2, 7.4, 7.0, 6.5, 6.6, 6.7, 6.0, 5.6, 6.0, 5.5]
}

z = pd.DataFrame(dados, columns = ['X', 'Y'])
correlacao = z.corr()
print(correlacao)
print('Correlação negativa e muito forte!')'''