# -*- coding: utf-8 -*-
"""Lista06Exercício01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17pVbpksp0m4aX4a6kjisPoTNmU3ItU7V
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 06

#EX01
'''import pandas as pd 
dados = {
    'Matemática':[60, 58, 73, 51, 21, 75, 48, 72, 75, 83, 62, 52],
    'Música':[80, 62, 70, 83, 62, 92, 79, 88, 54, 82, 64, 69]
}

x = pd.DataFrame(dados, columns = ['Matemática', 'Música'])
correlacao = x.corr()
print(correlacao)'''