# -*- coding: utf-8 -*-
"""Lista05Exercício02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DEEg8f945krF5dHLag8r3340S1zqNxvS
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 05

#EX02
'''#Fazendo a importação para utilização da função GMEAN
from scipy.stats.mstats import gmean
#Fazendo a importação do Statistics para untilização das funções
import statistics
#Preenchendo a lista com os dados de escala fornecidos
escala = [63, 67, 72, 75, 77, 77, 78, 80, 81]
#Utilizando a função MEAN para para exibir a Média aritmética simples
print('Méria aritmética simples: ', statistics.mean(escala))
#Utilizando a função HARMONIC_MEAN para para exibir a Média Harmônica
print('Média Harmônica: ', statistics.harmonic_mean(escala))
#Utilizando a função GMEAN para para exibir a Média Geometrica
print('Média Geométrica: ', gmean(escala))
#Utilizando a função MODE para para exibir a MODA
print('Moda: ', statistics.mode(escala))
#Utilizando a função MEDIAN para para exibir o Mediana
print('Mediana: ', statistics.median(escala))
#Utilizando a função VARIANCE para para exibir a Variância
print('Variância: ',statistics.variance(escala))
#Utilizando a função STDEV para para exibir o Desvio Padrão
print('Desvio Padrão: ',statistics.stdev(escala))'''