# -*- coding: utf-8 -*-
"""Lista06Exercício03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4O54dU6hyBn6Ghfjj1QOMzEJDpdgavM
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 06

#EX03
'''import pandas as pd 
dados = {
    'AnoServico':[2, 3, 4, 5, 4, 6, 7, 8, 8, 10],
    'Clientes':[48, 50, 56, 52, 43, 60, 62, 58, 64, 72]
}

x = pd.DataFrame(dados, columns = ['AnoServico', 'Clientes'])
correlacao = x.corr()
print(correlacao)
print('Correlação positiva e forte!')'''