# -*- coding: utf-8 -*-
"""Lista05Exercício01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1boymwJmtuEaTur4Kj-pGj89iEakNk-Di
"""

# Disciplina: Probabilidade e Estatística
# Aluno: Thiago Gonçalves Milanez Alves
# Matrícula: 20114290004
# Lista 05

#EX01
'''#Fazendo a importação para utilização da função GMEAN
from scipy.stats.mstats import gmean
#Fazendo a importação do Statistics para untilização das funções
import statistics
#Preenchendo a lista com os dados de consumo fornecidos
consumo = [7, 8, 9, 10, 11, 13, 13, 17]
#Utilizando a função MEAN para para exibir a Média aritmética simples
print('Média aritmética simples: ', statistics.mean(consumo))
#Utilizando a função HARMONIC_MEAN para para exibir a Média Harmônica
print('Média Harmônica: ', statistics.harmonic_mean(consumo))
#Utilizando a função GMEAN para para exibir a Média Geometrica
print('Média Geométrica: ', gmean(consumo))
#Utilizando a função MODE para para exibir a MODA
print('Moda: ', statistics.mode(consumo))
#Utilizando a função VARIANCE para para exibir a Variância
print('Variância: ',statistics.variance(consumo))
#Utilizando a função STDEV para para exibir o Desvio Padrão
print('Desvio Padrão: ',statistics.stdev(consumo))'''